# https://docs.gradle.org/current/userguide/version_catalogs.html#sec:version-catalog-declaration
[versions]
assertj = "4.0.0-M1"
junit = "6.0.1"
version-catalog-update = "1.0.1"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

[plugins]
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
